name: my_team
description: A new Flutter project.

flutter:
  uses-material-design: true
  assets:
    - assets/

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  redux: ^5.0.0
  cloud_firestore: ^4.9.1
  google_fonts: ^4.0.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.3
  json_serializable: ^6.5.1


